name: tc-metro

services:
  api:
    build:
      dockerfile: Dockerfile.dev
    environment:
      PORT: 8080
      STORAGE_PATH: ./transit
    volumes:
      - ./:/app
      - /app/node_modules
      - ./transit:/transit
    ports:
      - 9229:9229
      - 8080:8080
